development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://rediscloud:FBStYd4j8vIy0UK4@redis-19170.c8.us-east-1-3.ec2.cloud.redislabs.com:19170
  # url: redis://localhost:6379/1
